version: '3'

# Define services
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432

  backend-service:
    hostname: backend_service
    container_name: backend_service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=dev
      - SERVER_PORT=8080
      - SERVER_NAME=backend
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_CONNECTION_URL=postgres://izuhmncpslglsb:ce096c2a2beb33bffe5a808fb2348dee3f604513e0d9adafc0167d0ea828214b@ec2-54-234-13-16.compute-1.amazonaws.com:5432/d6qe0ng81n9d2n
      - DATABASE_CONNECTION_PORT=5432
    ports:
      - "8080:8080"
    restart: unless-stopped
