version: '3'

# Define services
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: local
      POSTGRES_DB: local
    expose:
      - 5432

  backend-service:
    hostname: backend_service
    container_name: backend_service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "7000:8080"
    restart: unless-stopped
