version: '3'

services:
  local:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"
    

  backend_service:
    env_file:
      - .env
    hostname: backend_service
    container_name: backend_service
    build:
      context: . 
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_NAME=${SERVER_NAME}
      - DATABASE_URL=${HEROKU_DATABASE_CONNECTION_URL}
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: ["sh", "-c", "env && sleep 3600"]
