version: '3'
      # - DATABASE_URL=${DATABASE_URL}
# Define services
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432:5432

  backend_service:
    env_file:
      - .env
    hostname: backend_service
    container_name: backend_service
    build:
      context: . 
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_NAME=${SERVER_NAME}
      - DATABASE_URL=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_CONNECTION_URL}/${DATABASE_NAME}?sslmode=require
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: ["sh", "-c", "env && sleep 3600"]

  db_seeder:
    build:
      context: .
      dockerfile: Dockerfile
      target: seeder
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    command: ./seed_db
