version: '3'

# Define services
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432

  backend-service:
    hostname: backend_service
    container_name: backend_service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=dev
      - SERVER_PORT=8080
      - SERVER_NAME=backend
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_CONNECTION_URL=postgres://ehxxgxaamkwsaz:15acfc1d3ddc307e898673d17a669f2169913ef6467380439410f045e42f3e4d@ec2-52-0-79-72.compute-1.amazonaws.com:5432/d7mdhbr0m054dr
      - DATABASE_CONNECTION_PORT=5432
    ports:
      - "8080:8080"
    restart: unless-stopped
