version: '3'

# Define services
services:
  postgres:   # database
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432:5432

  backend_service:  #backend
    env_file:
      - .env
    hostname: backend_service
    container_name: backend_service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_NAME=${SERVER_NAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_CONNECTION_URL=${DATABASE_CONNECTION_URL}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_CONNECTION_PORT=${DATABASE_CONNECTION_PORT}
    ports:
      - "8080:8080"
    restart: unless-stopped


