version: '3'

tasks:
  local:
    desc: "Run Docker Compose with the local database"
    vars:
      LOCAL_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
    cmds:
      - export $(grep -v '^#' .env | xargs) && DATABASE_URL={{.LOCAL_DATABASE_URL}} docker-compose --profile local up --build

  dev:
    desc: "Run Docker Compose with the Heroku database"
    cmds:
      - export $(grep -v '^#' .env | xargs) && DATABASE_URL=${HEROKU_DATABASE_URL} docker-compose --profile dev up --build

# tasks:
#   init-db-docker:
#     desc: Initialize PostgreSQL Docker image and volume
#     cmds:
#       - "[ -d postgres_data ] || mkdir postgres_data"
#       - docker run --name=postgres -p 5432:5432 -e POSTGRES_PASSWORD=root -e PGDATA=/var/lib/postgresql/data/pgdata --volume=`pwd`/postgres_data:/var/lib/postgresql/data -d postgres:13

#   create-db:
#     desc: Create empty local DB
#     cmds:
#       - sql-migrate up -config=db/create-database/empty.yml -env="local-postgres"

#   create-schema:
#     desc: Create schema for local DB
#     cmds:
#       - sql-migrate up -config=db/create-schema/dray.yml -env="local-postgres"

#   db-dump:
#     desc: dumps the dray schema to a SQL file, appends migration commands
#     cmds:
#       # Explanation of flags:
#       # -s schema only
#       # -O, no owner, don't assign tables, etc to a user/role
#       # -T gorp_migrations, exclude this table from the dump
#       - pg_dump -U postgres -d dray -h db -s -O -T  > db/dump.sql

#   drop-db:
#     desc: Drop local DB
#     cmds:
#       # At this time there is no ability to prompt before performing a command,
#       # but I brought this up in an issue to the project maintainer.
#       - sql-migrate down -config=db/create-database/empty.yml -env="local-postgres"

#   start-db:
#     desc: Start local DB container
#     cmds:
#       - docker start postgres

#   stop-db:
#     desc: Stop local DB container
#     cmds:
#       - docker stop postgres


