package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"github.com/Moral-Authority/backend/graph/model"
	"github.com/Moral-Authority/backend/handlers"
	"github.com/Moral-Authority/backend/database"
)

// AddCertification is the resolver for the addCertification field.
func (r *mutationResolver) AddCertification(ctx context.Context, input model.AddCertification) (*model.Certification, error) {
	dbService := database.CertificationDbServiceImpl{}
	cert, err := handlers.CertificationService{}.AddNewCertification(input, dbService)
	if err != nil {
		return cert, err
	}

	return cert, nil
}

// UpdateCertification is the resolver for the updateCertification field.
func (r *mutationResolver) UpdateCertification(ctx context.Context, input model.UpdateCertification) (*model.Certification, error) {
	dbService := database.CertificationDbServiceImpl{}
	certs, err := handlers.CertificationService{}.UpdateCertification(input, dbService)
	if err != nil {
		return certs, err
	}

	return nil, nil
}

func (r *queryResolver) GetAllCertifications(ctx context.Context) ([]*model.Certification, error) {
    dbService := database.CertificationDbServiceImpl{}
    certs, err := handlers.CertificationService{}.GetAllCertifications(dbService)
    if err != nil {
        return nil, fmt.Errorf("failed to retrieve certifications in resolver: %w", err)
    }

    return certs, nil
}
