package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/Moral-Authority/backend/database"
	"github.com/Moral-Authority/backend/graph/model"
	"github.com/Moral-Authority/backend/handlers"
)

// AddCompany is the resolver for the addCompany field.
func (r *mutationResolver) AddCompany(ctx context.Context, input model.AddCompany) (*model.Company, error) {
	company, err := handlers.CompanyService{}.AddCompany(input, database.CompanyDbServiceImpl{}, database.ImageDbServiceImpl{}, database.CertificationDbServiceImpl{})
	if err != nil {
		return nil, err
	}

	return company, nil
}

// UpdateCompany is the resolver for the updateCompany field.
func (r *mutationResolver) UpdateCompany(ctx context.Context, input model.UpdateCompany) (*model.Company, error) {
	dbService := database.CompanyDbServiceImpl{}
	company, err := handlers.CompanyService{}.UpdateCompany(dbService, input)
	if err != nil {
		return nil, err
	}
	return company, nil
}

// GetCompany is the resolver for the getCompany field.
func (r *queryResolver) GetCompany(ctx context.Context, id string) (*model.Company, error) {
	dbService := database.CompanyDbServiceImpl{}
	company, err := handlers.CompanyService{}.GetCompanyById(id, dbService)
	if err != nil {
		return nil, err
	}
	return company, nil
}

// GetAllCompanies is the resolver for the getAllCompanies field.
func (r *queryResolver) GetAllCompanies(ctx context.Context) ([]*model.Company, error) {
	dbService := database.CompanyDbServiceImpl{}
	companies, err := handlers.CompanyService{}.GetAllCompanies(dbService)
	if err != nil {
		return nil, err
	}
	return companies, nil
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mutationResolver) GetCompaniesByFilter(ctx context.Context, input model.FilterCompanyInput) ([]*model.Company, error) {
	dbService := database.CompanyDbServiceImpl{}

	filters := map[string]interface{}{
		"name":        input.Name,
		"city":        input.City,
		"state":       input.State,
		"country":     input.Country,
		"is_verified": input.IsVerified,
	}

	companies, err := handlers.CompanyService{}.GetCompaniesByFilter(dbService, filters)
	if err != nil {
		return nil, err
	}
	return companies, nil
}
