package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/Moral-Authority/backend/database"
	"github.com/Moral-Authority/backend/graph/model"
	"github.com/Moral-Authority/backend/models"
	"github.com/Moral-Authority/backend/handlers"
)

// AddProductCertification is the resolver for the addProductCertification field.
func (r *mutationResolver) AddCompanyCertification(ctx context.Context, input model.CompanyCertificationInput) (*models.CompanyCertification, error) {
	result, err := handlers.CompanyService{}.AddCompanyCertificationHandler(database.CompanyDbServiceImpl{}, database.CertificationDbServiceImpl{}, input)
	if err != nil {
		return nil, err
	}

	return result, nil
}
