package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"

	"github.com/Moral-Authority/backend/database"
	"github.com/Moral-Authority/backend/graph/model"
	"github.com/Moral-Authority/backend/handlers"
)

// AddCompany is the resolver for the addCompany field.
func (r *mutationResolver) AddCompany(ctx context.Context, request model.AddCompany) (*model.Company, error) {
	// TODO figure out err for companydbserviceimpl
	company, err := handlers.CompanyService{}.AddCompany(request, database.CompanyDbServiceImpl{}, database.ImageDbServiceImpl{}, database.CertificationDbServiceImpl{})
	if err != nil {
		return nil, err
	}

	return company, nil
}

// GetCompany is the resolver for the getCompany field.
func (r *queryResolver) GetCompany(ctx context.Context, id string) (*model.Company, error) {
	// TODO figure out err for companydbserviceimpl
	company, err := handlers.CompanyService{}.GetCompanyById(id, nil)
	if err != nil {
		return nil, err
	}
	return company, nil
}

// GetAllCompanies is the resolver for the getAllCompanies field.
func (r *queryResolver) GetAllCompanies(ctx context.Context) ([]*model.Company, error) {
	// TODO figure out err for companydbserviceimpl
	company, err := handlers.CompanyService{}.GetAllCompanies(nil)
	if err != nil {
		return nil, err
	}
	return company, nil
}
