package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/Moral-Authority/backend/database"
	"github.com/Moral-Authority/backend/graph/model"
	"github.com/Moral-Authority/backend/handlers"
)

// AddUserFav is the resolver for the addUserFav field.
func (r *mutationResolver) ToggleUserFav(ctx context.Context, request model.ToggleUserFav) ([]*model.Favorite, error) {
	fav, err := handlers.UserService{}.ToggleUserFav(request, database.UserDbServiceImpl{}, database.ProductDbServiceImpl{})
	if err != nil {
		return nil, err
	}

	return fav, nil
}
