package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/Moral-Authority/backend/graph/model"
)

// AddFav is the resolver for the addFav field.
func (r *mutationResolver) AddFav(ctx context.Context, request model.AddUserFav) ([]*model.Favourite, error) {
	panic(fmt.Errorf("not implemented: AddFav - addFav"))
}
