package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"

	"github.com/Moral-Authority/backend/database"
	"github.com/Moral-Authority/backend/graph/model"
	"github.com/Moral-Authority/backend/handlers"
)

// AddProduct is the resolver for the addProduct field.
func (r *mutationResolver) AddProduct(ctx context.Context, request model.AddProductRequest) (*model.Product, error) {
	product, err := handlers.ProductService{}.AddNewProduct(
		request,
		database.ProductDbServiceImpl{},
		database.ImageDbServiceImpl{},
	)
	if err == nil {
		return product, nil
	} else {
		return nil, err
	}
}
