package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/Moral-Authority/backend/database"
	"github.com/Moral-Authority/backend/graph/model"
	"github.com/Moral-Authority/backend/handlers"
)

// GetSubDepartmentFilters is the resolver for the getSubDepartmentFilters field.
func (r *queryResolver) GetSubDepartmentFilters(ctx context.Context, department string, subDepartment string) (*model.Filters, error) {
	result, err := handlers.ProductService{}.GetSubDepartmentFiltersHandler(ctx, department, subDepartment, database.ProductDbServiceImpl{})
	if err != nil {
		return nil, err
	}

	return result, nil
}
