package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/Moral-Authority/backend/database"
	"github.com/Moral-Authority/backend/graph/model"
	"github.com/Moral-Authority/backend/handlers"
	"github.com/sirupsen/logrus"
)

// AddUser is the resolver for the addUser field.
func (r *mutationResolver) AddUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	user, err := handlers.UserService{}.AddNewUserHandler(input, database.UserDbServiceImpl{})
	if err != nil {
		return nil, fmt.Errorf("failed to add user: %w", err)
	}
	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUser) (*model.User, error) {
	user, err := handlers.UserService{}.UpdateUserHandler(input, database.UserDbServiceImpl{}) // create an instance and pass it
	if err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}
	return user, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginUser) (*model.LoginResponse, error) {
	userService := handlers.UserService{}
	token, user, err := userService.LoginHandler(input, database.UserDbServiceImpl{})
	if err != nil {
		return nil, err
	}

	return &model.LoginResponse{
		Token: token,
		User:  user,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, id string) (*model.User, error) {
	userService := handlers.UserService{}
	_, err := userService.LogoutHandler(id, database.UserDbServiceImpl{})
	if err != nil {
		return nil, err
	}

	return nil, nil
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, email string) (string, error) {
	err := handlers.UserService{}.RequestPasswordResetHandler(email, database.UserDbServiceImpl{})
	if err != nil {
		return "", err
	}

	return "Password reset email sent", nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, token string, newPassword string) (string, error) {
	// Call the VerifyEmailHandler to process the token
	// err := handlers.UserService{}.UpdateUserHandler(token, newPassword, database.UserDbServiceImpl{})
	// if err != nil {
	// 	return "", err
	// }

	return "", nil
}

// VerifyEmail is the resolver for the VerifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (bool, error) {
	// Call the VerifyEmailHandler to process the token
	logrus.Infof("Token: %s", token)
	success, err := handlers.UserService{}.VerifyEmailHandler(token, database.UserDbServiceImpl{})
	if err != nil {
		return false, err
	}

	return success, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	user, err := handlers.UserService{}.GetUserByIdHandler(id, database.UserDbServiceImpl{}) // create an instance and pass it
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}
	return user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := handlers.UserService{}.GetUsers(database.UserDbServiceImpl{}) // create an instance and pass it
	if err != nil {
		return nil, fmt.Errorf("failed to get users: %w", err)
	}
	return users, nil
}
